apiVersion: v1
kind: Secret
metadata:
  name: nizam-secrets
  namespace: nizam
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://nizam:nizam@db:5432/nizam"
  JWT_SECRET: "nizam-k8s-secret-CHANGE-in-production"
  POSTGRES_USER: "nizam"
  POSTGRES_PASSWORD: "nizam"
  POSTGRES_DB: "nizam"
